Feature: Test the ineligibility screens

Try to get to the screens that show ineligibility.

Scenario: Just open the first page
    Given I start the interview "docassemble.playground42:juvenile-sealing-intro-9.yml"
    Then I click the button "Next "
    Then I should see the phrase "These questions are for sealing Massachusetts juvenile records."
    Then I click the button "No"
    Then I should see the phrase "This tool can only help with sealing juvenile records in Massachusetts."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I should see the phrase "Do you already have certified copies of the docket sheets for all of your cases?"
    Then I click the button "No"
    Then I should see the phrase "If you’re not a US citizen, it can be very important to have the copies for a hearing."
    Then I click the button "Yes, I’ll come back another time "
    Then I should see the phrase "We hope we could help a little."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I should see the phrase "Do you have any open criminal or juvenile cases right now anywhere in the USA?"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you have an open case you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I should see the phrase "Are you now on probation for any criminal or juvenile case in the USA"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you are on probation you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I click the button "No"
    Then I should see the phrase "Have you had any juvenile cases in any state in the USA"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you had a juvenile case in the USA in the past three years you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I should see the phrase "Have you been in juvenile custody anywhere in the USA"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you have been in juvenile custody in the USA in the past three years you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I should see the phrase "Have you had any convictions in any adult court in the USA"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you were convicted in the USA (in a state or federally) in the past three years you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I should see the phrase "Have you had any convictions in any federal court"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you were convicted in the USA (in a state or federally) in the past three years you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I should see the phrase "Were you in incarceration in the USA"
    Then I click the button "Yes"
    Then I should see the phrase "Sorry, but because you were incarcerated in the USA in the past three years you’re not eligible to get your juvenile record sealed."
    Then I click the button "Restart "
    Then I click the button "Next "
    Then I click the button "Yes"
    Then I click the button "Yes"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I click the button "No"
    Then I should see the phrase "We think you can probably seal your juvenile records."