on: [push]

jobs:
  aloe-tests:
    runs-on: ubuntu-latest

    name: Run tests
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./tests # Uses an action in the root directory
  puppeteer-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    name: Run tests
    steps:
      - name: Setup environment
        env: 
          PLAYGROUND_EMAIL: ${{ secrets.PLAYGROUND_EMAIL }}
          PLAYGROUND_PASSWORD: ${{ secrets.PLAYGROUND_PASSWORD }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
